export default [
    {
        key :'1',
        title:'首页',
        icon:'home',
        path:'/admin/home',
    },
    {
        key :'2',
        title:'用户管理',
        icon:'user',
        path:'/admin/user',
        children:[
            {
                key:'/admin/userlist',
                title:"查询用户",
                path:'/admin/userlist'
            },
            {
                key:'/admin/useradd',
                title:"用户添加",
                path:'/admin/useradd'
            },
        ]
    },
    {
        key:'3',
        title:"商品管理",
        icon: 'gift', 
        path:'/admin/goods',
        children:[
          {
            key:'/admin/goodsInfo',
            title:'商品信息',
            path:'/admin/goodsInfo'
          },
          {
            key:'/admin/goodsKind',
            title:'商品类别',
            path:'/admin/goodsKind'
          }
        ]
      },
      {
        key:'4',
        title:"员工管理",
        icon:'goods',
        path:'/admin/employee',
        children:[
          {
            key:'/admin/employee',
            title:'员工信息',
            path:'/admin/employee'
          },
          {
            key:'/admin/addEmployee',
            title:'添加员工',
            path:'/admin/addEmployee'
          }
        ]
      }
]